// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TOKENAPI.EF;

#nullable disable

namespace TOKENAPI.Migrations
{
    [DbContext(typeof(DbCtx))]
    partial class DbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TOKENAPI.Domain.Acct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<string>("Addr")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<long>("LPTime")
                        .HasColumnType("bigint");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("PA_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PA_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PA_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PA_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PA_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PA_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PoolAlloc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PoolPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PoolPlus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PoolRwd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PoolUnc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<int>("R1")
                        .HasColumnType("int");

                    b.Property<int>("R2")
                        .HasColumnType("int");

                    b.Property<int>("R3")
                        .HasColumnType("int");

                    b.Property<int>("R4")
                        .HasColumnType("int");

                    b.Property<int>("R5")
                        .HasColumnType("int");

                    b.Property<int>("R6")
                        .HasColumnType("int");

                    b.Property<long?>("RId")
                        .HasColumnType("bigint");

                    b.Property<string>("RefAddr")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("RefAlloc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RefClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RefCur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<long?>("RefId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RefReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RefUnc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("Staking")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("StkAmt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("StkClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("StkRewards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<long>("StkTime")
                        .HasColumnType("bigint");

                    b.Property<decimal>("StkUnc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TA_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TA_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TA_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TA_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TA_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TA_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TC_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TC_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TC_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TC_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TC_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TC_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<int>("TM_1")
                        .HasColumnType("int");

                    b.Property<int>("TM_2")
                        .HasColumnType("int");

                    b.Property<int>("TM_3")
                        .HasColumnType("int");

                    b.Property<int>("TM_4")
                        .HasColumnType("int");

                    b.Property<int>("TM_5")
                        .HasColumnType("int");

                    b.Property<int>("TM_6")
                        .HasColumnType("int");

                    b.Property<decimal>("TP_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TP_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TP_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TP_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TP_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TP_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TQ_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TQ_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TQ_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TQ_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TQ_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TQ_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TS_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TS_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TS_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TS_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TS_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TS_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TU_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TU_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TU_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TU_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TU_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TU_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("Uptd")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UsrId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("acct");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Addr = "0x7D55Ba861B5BBf5B7C9C6196dEd6962000582Dcc",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 0,
                            R2 = 0,
                            R3 = 0,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 0L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 0L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 1310895264L
                        },
                        new
                        {
                            Id = 2L,
                            Addr = "0x8fb5BEf92cd481eCAcc87fEA4aa9470b47d19972",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 1,
                            R2 = 0,
                            R3 = 0,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 1L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 1310895264L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 6712105348L
                        },
                        new
                        {
                            Id = 3L,
                            Addr = "0x64640eACccCCFfA22Ef6FF39D9D2806Dc13D366A",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 1,
                            R2 = 0,
                            R3 = 0,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 1L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 1310895264L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 1657410923L
                        },
                        new
                        {
                            Id = 4L,
                            Addr = "0x54557b156ad1F87e44c177dC2609781EE8A449E1",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 2,
                            R2 = 1,
                            R3 = 0,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 2L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 6712105348L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 3945110278L
                        },
                        new
                        {
                            Id = 5L,
                            Addr = "0xA8f88F9051c444310A71F791f04ac38d12B82B6A",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 2,
                            R2 = 1,
                            R3 = 0,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 2L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 6712105348L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 8537692104L
                        },
                        new
                        {
                            Id = 6L,
                            Addr = "0xAD8EB429B12aCBa6daeAB237278fAE90F231feDD",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 5,
                            R2 = 2,
                            R3 = 1,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 5L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 8537692104L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 7261081493L
                        },
                        new
                        {
                            Id = 7L,
                            Addr = "0x1D9cDdC3F51DBD880b4B1D2F1f882b3EB13fc81f",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 6,
                            R2 = 5,
                            R3 = 2,
                            R4 = 1,
                            R5 = 0,
                            R6 = 0,
                            RId = 6L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 7261081493L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 3749862658L
                        },
                        new
                        {
                            Id = 8L,
                            Addr = "0x23c4adA813a80EdFCdfE7d8f7Aa95F5a4Ce98FBb",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 6,
                            R2 = 5,
                            R3 = 2,
                            R4 = 1,
                            R5 = 0,
                            R6 = 0,
                            RId = 6L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 7261081493L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 6195102873L
                        },
                        new
                        {
                            Id = 9L,
                            Addr = "0xEFBb333b1F19b7F953fac9F4165b827191586284",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 6,
                            R2 = 5,
                            R3 = 2,
                            R4 = 1,
                            R5 = 0,
                            R6 = 0,
                            RId = 6L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 7261081493L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 9152106487L
                        },
                        new
                        {
                            Id = 10L,
                            Addr = "0x4475a92cA5C8Aa534A5fb811Baa7dB943CFe98D0",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 3,
                            R2 = 1,
                            R3 = 0,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 3L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 1657410923L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 4710361958L
                        },
                        new
                        {
                            Id = 11L,
                            Addr = "0x62e024JH89334K0De770FF24524b99FJ9F348J43",
                            LPTime = 0L,
                            Level = (byte)1,
                            PA_1 = 0m,
                            PA_2 = 0m,
                            PA_3 = 0m,
                            PA_4 = 0m,
                            PA_5 = 0m,
                            PA_6 = 0m,
                            PoolAlloc = 0m,
                            PoolPaid = 0m,
                            PoolPlus = 0m,
                            PoolRwd = 0m,
                            PoolUnc = 0m,
                            R1 = 10,
                            R2 = 3,
                            R3 = 1,
                            R4 = 0,
                            R5 = 0,
                            R6 = 0,
                            RId = 10L,
                            RefAlloc = 0m,
                            RefClaimed = 0m,
                            RefCur = 0m,
                            RefId = 4710361958L,
                            RefReward = 0m,
                            RefUnc = 0m,
                            Staking = false,
                            StkAmt = 0m,
                            StkClaimed = 0m,
                            StkRewards = 0m,
                            StkTime = 0L,
                            StkUnc = 0m,
                            TA_1 = 0m,
                            TA_2 = 0m,
                            TA_3 = 0m,
                            TA_4 = 0m,
                            TA_5 = 0m,
                            TA_6 = 0m,
                            TC_1 = 0m,
                            TC_2 = 0m,
                            TC_3 = 0m,
                            TC_4 = 0m,
                            TC_5 = 0m,
                            TC_6 = 0m,
                            TM_1 = 0,
                            TM_2 = 0,
                            TM_3 = 0,
                            TM_4 = 0,
                            TM_5 = 0,
                            TM_6 = 0,
                            TP_1 = 0m,
                            TP_2 = 0m,
                            TP_3 = 0m,
                            TP_4 = 0m,
                            TP_5 = 0m,
                            TP_6 = 0m,
                            TQ_1 = 0m,
                            TQ_2 = 0m,
                            TQ_3 = 0m,
                            TQ_4 = 0m,
                            TQ_5 = 0m,
                            TQ_6 = 0m,
                            TS_1 = 0m,
                            TS_2 = 0m,
                            TS_3 = 0m,
                            TS_4 = 0m,
                            TS_5 = 0m,
                            TS_6 = 0m,
                            TU_1 = 0m,
                            TU_2 = 0m,
                            TU_3 = 0m,
                            TU_4 = 0m,
                            TU_5 = 0m,
                            TU_6 = 0m,
                            Uptd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsrId = 9897761958L
                        });
                });

            modelBuilder.Entity("TOKENAPI.Domain.EvtApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("blockno")
                        .HasColumnType("bigint");

                    b.Property<double>("bnbamt")
                        .HasColumnType("double");

                    b.Property<decimal>("bnbamt_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<long>("crtd")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crtd_")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("owner")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("proc")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("tokenamt")
                        .HasColumnType("double");

                    b.Property<decimal>("tokenamt_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("evt_approval");
                });

            modelBuilder.Entity("TOKENAPI.Domain.EvtClaimed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<decimal>("amount_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<long>("blockno")
                        .HasColumnType("bigint");

                    b.Property<long>("crtd")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crtd_")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("proc")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("timestamp")
                        .HasColumnType("double");

                    b.Property<DateTime>("timestamp_")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.Property<decimal>("total_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("unamt")
                        .HasColumnType("double");

                    b.Property<decimal>("unamt_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("evt_claimed");
                });

            modelBuilder.Entity("TOKENAPI.Domain.EvtPurchased", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("blockno")
                        .HasColumnType("bigint");

                    b.Property<long>("crtd")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crtd_")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("owner")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("proc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("spender")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("value")
                        .HasColumnType("double");

                    b.Property<decimal>("value_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("evt_purchased");
                });

            modelBuilder.Entity("TOKENAPI.Domain.EvtStaked", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<decimal>("amount_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<ulong>("blockno")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("crtd")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("crtd_")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("proc")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("timestamp")
                        .HasColumnType("double");

                    b.Property<DateTime>("timestamp_")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.Property<decimal>("total_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("unamt")
                        .HasColumnType("double");

                    b.Property<decimal>("unamt_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("evt_staked");
                });

            modelBuilder.Entity("TOKENAPI.Domain.EvtTransfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("blockno")
                        .HasColumnType("bigint");

                    b.Property<long>("crtd")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crtd_")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("from")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("proc")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("to")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("value")
                        .HasColumnType("double");

                    b.Property<decimal>("value_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("evt_transfer");
                });

            modelBuilder.Entity("TOKENAPI.Domain.EvtUnstaked", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<decimal>("amount_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<ulong>("blockno")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("crtd")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("crtd_")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("proc")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("timestamp")
                        .HasColumnType("double");

                    b.Property<DateTime>("timestamp_")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.Property<decimal>("total_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("unamt")
                        .HasColumnType("double");

                    b.Property<decimal>("unamt_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("evt_unstaked");
                });

            modelBuilder.Entity("TOKENAPI.Domain.Level", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<decimal>("FPH_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPH_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPH_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPH_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPH_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPH_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPS_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPS_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPS_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPS_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPS_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("FPS_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LM_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LM_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LM_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LM_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LM_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LM_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("LN_1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("LN_2")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("LN_3")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("LN_4")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("LN_5")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("LN_6")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("LP_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LP_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LP_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LP_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LP_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LP_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LU_1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LU_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LU_3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LU_4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LU_5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("LU_6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("MINS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PLOC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("POOLMIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,12)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("PRPP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(38,16)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RLOC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RPH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RPS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,18)")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("level");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FPH_1 = 0.0000062499999999999999999600m,
                            FPH_2 = 0.0000050000000000000000000400m,
                            FPH_3 = 0.0000037500000000000000001200m,
                            FPH_4 = 0.0000024999999999999999998400m,
                            FPH_5 = 0.0000012499999999999999999200m,
                            FPH_6 = 0.0000006249999999999999999600m,
                            FPS_1 = 0.0000000017361111111111111111m,
                            FPS_2 = 0.0000000013888888888888888889m,
                            FPS_3 = 0.0000000010416666666666666667m,
                            FPS_4 = 0.0000000006944444444444444444m,
                            FPS_5 = 0.0000000003472222222222222222m,
                            FPS_6 = 0.0000000001736111111111111111m,
                            LM_1 = 50000m,
                            LM_2 = 200000m,
                            LM_3 = 500000m,
                            LM_4 = 1000000m,
                            LM_5 = 2000000m,
                            LM_6 = 3000000m,
                            LN_1 = "Level 1",
                            LN_2 = "Level 2",
                            LN_3 = "Level 3",
                            LN_4 = "Level 4",
                            LN_5 = "Level 5",
                            LN_6 = "Level 6",
                            LP_1 = 5m,
                            LP_2 = 4m,
                            LP_3 = 3m,
                            LP_4 = 2m,
                            LP_5 = 1m,
                            LP_6 = 0.5m,
                            LU_1 = 125m,
                            LU_2 = 500m,
                            LU_3 = 1250m,
                            LU_4 = 2500m,
                            LU_5 = 5000m,
                            LU_6 = 10000m,
                            MINS = 10000m,
                            PLOC = 0.0020833333333333333333333333m,
                            POOLMIN = 300000m,
                            PRPP = 0.0000002604166666666666668000m,
                            RLOC = 0.15m,
                            RPH = 0.0001249999999999999999999200m,
                            RPS = 0.0000000347222222222222222222m
                        });
                });

            modelBuilder.Entity("TOKENAPI.Domain.ProClaimed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<decimal>("amount_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<long>("blockno")
                        .HasColumnType("bigint");

                    b.Property<long>("crtd")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crtd_")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("proc")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("timestamp")
                        .HasColumnType("double");

                    b.Property<DateTime>("timestamp_")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.Property<decimal>("total_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("unamt")
                        .HasColumnType("double");

                    b.Property<decimal>("unamt_")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("pro_claimed");
                });

            modelBuilder.Entity("TOKENAPI.Domain.ProPoolCom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<decimal>("amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,12)")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("crtd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ethfee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(24,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("fees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(24,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,12)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("pro_poolcom");
                });

            modelBuilder.Entity("TOKENAPI.Domain.ProRefCom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<decimal>("amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,12)")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("crtd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ethfee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(24,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("fees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(24,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,12)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("pro_refcom");
                });

            modelBuilder.Entity("TOKENAPI.Domain.ProStaked", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<ulong>("blockno")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("crtd")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("unamt")
                        .HasColumnType("double");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("pro_staked");
                });

            modelBuilder.Entity("TOKENAPI.Domain.ProUnstaked", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<ulong>("blockno")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("crtd")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.Property<string>("txid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double>("unamt")
                        .HasColumnType("double");

                    b.Property<string>("user")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("pro_unstaked");
                });

            modelBuilder.Entity("TOKENAPI.Domain.Stats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Daily_LR")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("Daily_LRMK")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("Daily_NR")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("Daily_NRMK")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("Hourly_LR")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("Hourly_LRMK")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("Hourly_NR")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("Hourly_NRMK")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("PoolPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RefPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("RwdPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TknPrc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(24,12)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("TknSupply")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(36,6)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("WdrwFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,4)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("WdrwMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,4)")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id");

                    b.ToTable("stats");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Daily_LR = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Daily_LRMK = 0ul,
                            Daily_NR = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Daily_NRMK = 0ul,
                            Hourly_LR = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hourly_LRMK = 0ul,
                            Hourly_NR = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hourly_NRMK = 0ul,
                            PoolPaid = 0m,
                            RefPaid = 0m,
                            RwdPaid = 0m,
                            TknPrc = 0.0005m,
                            TknSupply = 10000000000m,
                            WdrwFee = 10.0m,
                            WdrwMin = 1.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
